In [163]:
import numpy as np

In [164]:
lat_x = lat_y = lat_z = lat_t = 32
lat_p=2
lat_d=4
lat_cc=9
_EVEN_ODD_ = 2
lat_x /= 2
x = 5
y = 9
z = 0
t = 31
parity = 1

In [165]:
i = 0

In [166]:
((((parity * lat_t + t) * lat_z + z) * lat_y + y) * lat_x + x)

1032341.0

In [167]:
(((((3 * _EVEN_ODD_ + parity) * lat_t + t) * lat_z + z) * lat_y + y) *
 lat_x +
 x)

4178069.0

In [168]:
idx = ((((t) * lat_z + z) * lat_y + y) * lat_x + x)
idx

508053.0

In [169]:
((((parity * lat_t + t) * lat_z + z) * lat_y + y) * lat_x + x)

1032341.0

In [170]:
def print_index(_):
    print("##", _)
    __ = _ % lat_x
    _ -= (__)
    _ /= lat_x
    print("##", _)
    print("@x:", __)
    __ = _ % lat_y
    _ -= (__)
    _ /= lat_y
    print("##", _)
    print("@y:", __)
    __ = _ % lat_z
    _ -= (__)
    _ /= lat_z
    print("##", _)
    print("@z:", __)
    __ = _ % lat_t
    _ -= (__)
    _ /= lat_t
    print("##", _)
    print("@t:", __)
    __ = _ % lat_p
    _ -= (__)
    _ /= lat_p
    print("##", _)
    print("@p:", __)
    __ = _ % lat_d
    _ -= (__)
    _ /= lat_d
    print("##", _)
    print("@d:", __)
    __ = _ % lat_cc
    _ -= (__)
    _ /= lat_cc
    print("##", _)
    print("@cc:", __)

In [171]:
_ = 9291069


In [172]:
_ = 37602621
print("##", _)
__ = _ % lat_x
_ -= (__)
_ /= lat_x
print("##", _)
print("@x:", __)
__ = _ % lat_y
_ -= (__)
_ /= lat_y
print("##", _)
print("@y:", __)
__ = _ % lat_z
_ -= (__)
_ /= lat_z
print("##", _)
print("@z:", __)
__ = _ % lat_t
_ -= (__)
_ /= lat_t
print("##", _)
print("@t:", __)
__ = _ % lat_p
_ -= (__)
_ /= lat_p
print("##", _)
print("@p:", __)
__ = _ % lat_d
_ -= (__)
_ /= lat_d
print("##", _)
print("@d:", __)
__ = _ % lat_cc
_ -= (__)
_ /= lat_cc
print("##", _)
print("@cc:", __)

## 37602621
## 2350163.0
@x: 13.0
## 73442.0
@y: 19.0
## 2295.0
@z: 2.0
## 71.0
@t: 23.0
## 35.0
@p: 1.0
## 8.0
@d: 3.0
## 0.0
@cc: 8.0


In [173]:
import numpy as np
N=9
D=np.arange(N**2,dtype=complex).reshape(N,N)
D.imag=D*0.5
D

/tmp/ipykernel_3290/3886492396.py:4: ComplexWarning: Casting complex values to real discards the imaginary part
  D.imag=D*0.5


array([[ 0. +0.j ,  1. +0.5j,  2. +1.j ,  3. +1.5j,  4. +2.j ,  5. +2.5j,
         6. +3.j ,  7. +3.5j,  8. +4.j ],
       [ 9. +4.5j, 10. +5.j , 11. +5.5j, 12. +6.j , 13. +6.5j, 14. +7.j ,
        15. +7.5j, 16. +8.j , 17. +8.5j],
       [18. +9.j , 19. +9.5j, 20.+10.j , 21.+10.5j, 22.+11.j , 23.+11.5j,
        24.+12.j , 25.+12.5j, 26.+13.j ],
       [27.+13.5j, 28.+14.j , 29.+14.5j, 30.+15.j , 31.+15.5j, 32.+16.j ,
        33.+16.5j, 34.+17.j , 35.+17.5j],
       [36.+18.j , 37.+18.5j, 38.+19.j , 39.+19.5j, 40.+20.j , 41.+20.5j,
        42.+21.j , 43.+21.5j, 44.+22.j ],
       [45.+22.5j, 46.+23.j , 47.+23.5j, 48.+24.j , 49.+24.5j, 50.+25.j ,
        51.+25.5j, 52.+26.j , 53.+26.5j],
       [54.+27.j , 55.+27.5j, 56.+28.j , 57.+28.5j, 58.+29.j , 59.+29.5j,
        60.+30.j , 61.+30.5j, 62.+31.j ],
       [63.+31.5j, 64.+32.j , 65.+32.5j, 66.+33.j , 67.+33.5j, 68.+34.j ,
        69.+34.5j, 70.+35.j , 71.+35.5j],
       [72.+36.j , 73.+36.5j, 74.+37.j , 75.+37.5j, 76.+38.j , 77.+38.5j

In [174]:
x=np.arange(N,dtype=complex)
x.imag=x*3
x

/tmp/ipykernel_3290/2337084737.py:2: ComplexWarning: Casting complex values to real discards the imaginary part
  x.imag=x*3


array([0. +0.j, 1. +3.j, 2. +6.j, 3. +9.j, 4.+12.j, 5.+15.j, 6.+18.j,
       7.+21.j, 8.+24.j])

In [175]:
D@x

array([ -102. +714.j,  -264.+1848.j,  -426.+2982.j,  -588.+4116.j,
        -750.+5250.j,  -912.+6384.j, -1074.+7518.j, -1236.+8652.j,
       -1398.+9786.j])

In [176]:
D_conj=D.conj()
D_dag=D_conj.T
D_dag

array([[ 0. -0.j ,  9. -4.5j, 18. -9.j , 27.-13.5j, 36.-18.j , 45.-22.5j,
        54.-27.j , 63.-31.5j, 72.-36.j ],
       [ 1. -0.5j, 10. -5.j , 19. -9.5j, 28.-14.j , 37.-18.5j, 46.-23.j ,
        55.-27.5j, 64.-32.j , 73.-36.5j],
       [ 2. -1.j , 11. -5.5j, 20.-10.j , 29.-14.5j, 38.-19.j , 47.-23.5j,
        56.-28.j , 65.-32.5j, 74.-37.j ],
       [ 3. -1.5j, 12. -6.j , 21.-10.5j, 30.-15.j , 39.-19.5j, 48.-24.j ,
        57.-28.5j, 66.-33.j , 75.-37.5j],
       [ 4. -2.j , 13. -6.5j, 22.-11.j , 31.-15.5j, 40.-20.j , 49.-24.5j,
        58.-29.j , 67.-33.5j, 76.-38.j ],
       [ 5. -2.5j, 14. -7.j , 23.-11.5j, 32.-16.j , 41.-20.5j, 50.-25.j ,
        59.-29.5j, 68.-34.j , 77.-38.5j],
       [ 6. -3.j , 15. -7.5j, 24.-12.j , 33.-16.5j, 42.-21.j , 51.-25.5j,
        60.-30.j , 69.-34.5j, 78.-39.j ],
       [ 7. -3.5j, 16. -8.j , 25.-12.5j, 34.-17.j , 43.-21.5j, 52.-26.j ,
        61.-30.5j, 70.-35.j , 79.-39.5j],
       [ 8. -4.j , 17. -8.5j, 26.-13.j , 35.-17.5j, 44.-22.j , 53.-26.5j

In [177]:
x_conj=x.conj()
x_dag=x_conj.reshape(1,N)
x_dag

array([[0. -0.j, 1. -3.j, 2. -6.j, 3. -9.j, 4.-12.j, 5.-15.j, 6.-18.j,
        7.-21.j, 8.-24.j]])

In [178]:
D_dag@x

array([4590.+4590.j, 4680.+4680.j, 4770.+4770.j, 4860.+4860.j,
       4950.+4950.j, 5040.+5040.j, 5130.+5130.j, 5220.+5220.j,
       5310.+5310.j])

In [179]:
D_conj@x

array([ 510. +510.j, 1320.+1320.j, 2130.+2130.j, 2940.+2940.j,
       3750.+3750.j, 4560.+4560.j, 5370.+5370.j, 6180.+6180.j,
       6990.+6990.j])